name: Wiphala
favicon: null
layout_spectrum: 0.2537904947530478
typography_spectrum: 0.6658729361370206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.38604128174483776
  lightness: 0.1502993346657604
  saturation: 0.522584265563637
  rhythmicContrast: 0.20120681216940284
purpose: []
